### ISSUE TITLE
群聊禁用功能无效果

### ISSUE THREAD

**Issue by bugcatcapoo** [Jigsaw111/nonebot_plugin_manager#10]
如图：
![image](https://user-images.githubusercontent.com/104308239/169696765-ca908412-c015-4680-ae03-af6aebdf3fbe.png)

![image](https://user-images.githubusercontent.com/104308239/169696796-cfa587ea-89bb-4404-9401-824a16953d4e.png)

**Comment by j1g5awi** [comment]
Matcher 预处理函数不知如何没有触发，方便提供下 Python 版本、NoneBot2 版本、nonebot-plugin-manager 版本吗？

**Comment by bugcatcapoo** [comment]
我更新了一下插件，似乎就可以了
打扰您了>3
