### ISSUE TITLE
关于插件信息的更新机制

### ISSUE THREAD

**Issue by MeetWq** [Jigsaw111/nonebot_plugin_manager#11]
若某个插件因bug导致某次启动没有被加载，会导致npm记录的权限信息被清空，感觉很不友好
能否避免类似的情况？
真寻好像有个连续5次加载失败再清空插件数据的机制

**Comment by j1g5awi** [comment]
累计数据太麻烦了，直接不删了！

~~其实 npm 即将迎来重构，懒得加新功能了。~~
