### ISSUE TITLE
建议将私聊和默认群号分开

### ISSUE THREAD

**Issue by MeetWq** [Jigsaw111/nonebot_plugin_manager#2]
起初我以为 群号"0" 是控制插件默认开启还是关闭的，后来发现对私聊也有影响😂

**Comment by j1g5awi** [comment]
因为我当初为了省事就这样做了 要不还得给私聊/默认再分一个 key。
下个版本改下吧，把默认放到 "default" 这个 key 里。

**Comment by MeetWq** [comment]
👍神速啊

**Comment by j1g5awi** [comment]
> 👍神速啊

本来就不是什么麻烦事，把所有的 "0" 替换成 "default" 就行了。

不过由于 nonebot 新版本的原因，模块识别有一些 bug，建议把 nonebot 停留在 2.0.0a11 。
