### ISSUE TITLE
求帮助

### ISSUE THREAD

**Issue by Xiao-yux** [Jigsaw111/nonebot_plugin_manager#20]
![image](https://user-images.githubusercontent.com/79674967/218234633-8fac5d8d-1d6b-453f-91d3-c6a3c432303c.png)
![image](https://user-images.githubusercontent.com/79674967/218234657-4c59805a-2394-44eb-b2a6-f6795cc977cc.png)
为什么不加/无法触发啊，以前都还可以的

**Comment by j1g5awi** [comment]
请确定你的 `COMMAND_START` 配置起了作用，在 DEBUG 模式下可以在 NoneBot2 启动时看到 `[DEBUG] nonebot | Loaded Config: `

**Comment by Yunmo-1** [comment]
![image](https://user-images.githubusercontent.com/79674967/218244677-1c105b4b-49b1-43f9-9083-5c2ed6ff4083.png)

**Comment by Xiao-yux** [comment]
![image](https://user-images.githubusercontent.com/79674967/218244694-c78aa827-8b81-43a7-a01f-cf0208bd3191.png)

**Comment by Xiao-yux** [comment]
![image](https://user-images.githubusercontent.com/79674967/218244815-8149a245-91ff-45de-a8ea-9c54af9dbbcf.png)

**Comment by Xiao-yux** [comment]
我知道是什么问题了
![image](https://user-images.githubusercontent.com/79674967/218244919-ed8ca77d-8b8b-4ce7-9d66-2f65d4b4ab91.png)

**Comment by Xiao-yux** [comment]
感觉是群聊学习这个插件的锅

**Comment by j1g5awi** [comment]
请你在 DEBUG 模式下分别用 `npm` `/npm`  给 Bot 发消息，然后把日志发上来。

**Comment by j1g5awi** [comment]
> 感觉是群聊学习这个插件的锅

对，它会自动删除为空的命令前缀。

**Comment by Xiao-yux** [comment]
删了群聊学习就解决了。。。
