### ISSUE TITLE
插件读权限的问题

### ISSUE THREAD

**Issue by MeetWq** [Jigsaw111/nonebot_plugin_manager#4]
https://github.com/nonepkg/nonebot-plugin-manager/blob/4b119da1e1dd017a30c3e0ffeeed1987a1c16a19/nonebot_plugin_manager/manager.py#L124

为何一定要给插件加上读权限呢？我想实现某些插件默认不可见，但是把模式设成”711“后又会被自动改成”755“

**Comment by j1g5awi** [comment]
Let me see see. 这行代码的本意应该是如果一个插件原先有 matcher 现在没有 matcher，就调为不可见；反之则调为可见。结果忘记检测用户是否手动更改了可见性，导致无论用户改没改过都要强制矫正。

**Comment by j1g5awi** [comment]
看来还是得新增一个字段来存储是否有 matcher，不能图省事跟 mode 二合一。
