### ISSUE TITLE
npm info 报错

### ISSUE THREAD

**Issue by Superskyyy** [Jigsaw111/nonebot_plugin_manager#5]
![image](https://user-images.githubusercontent.com/26076517/156093200-5d8cccac-dc7b-4fac-865f-848eeb768154.png)
在群内执行 npm info 插件名会出现报错 无qq端错误信息输出

**Comment by j1g5awi** [comment]
NoneBot 文档的路径改了，插件 POST 到了 404，我有空改一下吧。

**Comment by j1g5awi** [comment]
Fix in 1feb0f87df9ba685380748063b0b446d1b094208
